export const MOCK_ASPIRATIONS_DATA = [
  {
    id: "ASP-001",
    title: "Perbaikan Jalan Berlubang di Jl. Merdeka",
    description: "Terdapat banyak lubang di sepanjang jalan Merdeka yang membahayakan pengendara motor, terutama saat hujan karena tertutup genangan air. Mohon segera diperbaiki.",
    author: "Budi Santoso",
    address: "Jl. Merdeka No 12, Semarang",
    phone: "0812-3456-7890",
    time: "2 jam yang lalu",
    category: "Infrastruktur",
    status: "Menunggu Approval",
    initialUpvotes: 124,
    comments: 2,
    jarak: 85,
    urgensi: 90,
    createdAt: new Date().toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-002",
    title: "Lampu Jalan Mati di Komplek Mawar",
    description: "Sudah 3 hari lampu penerangan jalan di blok C mati. Kondisi sangat gelap di malam hari dan rawan tindak kejahatan.",
    author: "Siti Aminah",
    address: "Komplek Mawar Blok C4",
    phone: "0813-9876-5432",
    time: "5 jam yang lalu",
    category: "Fasilitas Umum",
    status: "Menunggu Approval",
    initialUpvotes: 45,
    comments: 0,
    jarak: 60,
    urgensi: 70,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-003",
    title: "Puskesmas di Desa Sumberrejo Kekurangan Obat",
    description: "Obat-obatan di puskesmas desa Sumberejo sudah hampir habis, terutama untuk penyakit demam berdarah. Tolong segera di-restock.",
    author: "Ahmad Rizki",
    address: "Desa Sumberrejo RT 02/01",
    phone: "0856-1122-3344",
    time: "1 hari yang lalu",
    category: "Kesehatan",
    status: "Menunggu Approval",
    initialUpvotes: 32,
    comments: 1,
    jarak: 40,
    urgensi: 65,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-004",
    title: "Kekurangan Ruang Kelas di SDN 01",
    description: "Jumlah siswa sudah melebihi kapasitas, sehingga ruang kelas terasa sangat sempit dan tidak nyaman. Butuh penambahan kelas baru.",
    author: "Dewi Lestari",
    address: "Kecamatan Ngaliyan",
    phone: "0819-5566-7788",
    time: "1 hari yang lalu",
    category: "Pendidikan",
    status: "Menunggu Approval",
    initialUpvotes: 18,
    comments: 0,
    jarak: 30,
    urgensi: 50,
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-005",
    title: "Banjir di Kawasan Pasar Induk",
    description: "Selokan di sekitar pasar induk mampet oleh sampah, sehingga setiap hujan lebat pasti banjir setinggi lutut dan merusak dagangan.",
    author: "Rudi Hartono",
    time: "2 hari yang lalu",
    category: "Lingkungan",
    status: "Menunggu Approval",
    initialUpvotes: 210,
    comments: 15,
    jarak: 95,
    urgensi: 95,
    createdAt: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-006",
    title: "Kemacetan Parah di Persimpangan Tugu",
    description: "Lampu lalu lintas di persimpangan tugu sering error dan tidak sinkron, menyebabkan kemacetan parah setiap jam berangkat kerja.",
    author: "Maya Indasari",
    time: "3 hari yang lalu",
    category: "Transportasi",
    status: "Diteruskan ke Dinas",
    initialUpvotes: 88,
    comments: 4,
    jarak: 75,
    urgensi: 80,
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    forwardedTo: "Dinas Perhubungan"
  },
  {
    id: "ASP-007",
    title: "Pungli di Layanan Pembuatan KTP",
    description: "Terdapat oknum yang meminta biaya tambahan tidak resmi untuk mempercepat proses pembuatan KTP di kelurahan.",
    author: "Anonim",
    time: "3 hari yang lalu",
    category: "Pelayanan Publik",
    status: "Menunggu Approval",
    initialUpvotes: 305,
    comments: 42,
    jarak: 85,
    urgensi: 100,
    createdAt: new Date(Date.now() - 75 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-008",
    title: "Taman Bermain Anak Rusak",
    description: "Fasilitas ayunan dan perosotan di taman kota banyak yang berkarat dan patah. Sangat berbahaya bagi anak-anak yang bermain.",
    author: "Lisa Kumala",
    time: "4 hari yang lalu",
    category: "Fasilitas Umum",
    status: "Menunggu Approval",
    initialUpvotes: 56,
    comments: 2,
    jarak: 45,
    urgensi: 55,
    createdAt: new Date(Date.now() - 96 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-009",
    title: "Pencemaran Limbah Pabrik di Sungai",
    description: "Air sungai di desa kami berubah warna menjadi hitam dan berbau menyengat. Diduga akibat limbah pabrik tekstil yang membuang sembarangan.",
    author: "Hendra Wijaya",
    time: "5 hari yang lalu",
    category: "Lingkungan",
    status: "Menunggu Approval",
    initialUpvotes: 180,
    comments: 20,
    jarak: 90,
    urgensi: 95,
    createdAt: new Date(Date.now() - 120 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-010",
    title: "Kurangnya Tenaga Medis di RSUD",
    description: "Antrean IGD sangat membludak namun dokter jaga hanya sedikit, banyak pasien terlantar hingga berjam-jam tanpa penanganan awal.",
    author: "Tari Lestari",
    time: "6 hari yang lalu",
    category: "Kesehatan",
    status: "Menunggu Approval",
    initialUpvotes: 145,
    comments: 11,
    jarak: 80,
    urgensi: 85,
    createdAt: new Date(Date.now() - 144 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-011",
    title: "Atap Pasar Tradisional Bocor",
    description: "Banyak atap los penjual sayur yang bocor saat hujan deras. Mohon revitalisasi pasar segera dilanjutkan.",
    author: "Joko Anwar",
    time: "1 minggu yang lalu",
    category: "Ekonomi",
    status: "Selesai",
    initialUpvotes: 67,
    comments: 5,
    jarak: 65,
    urgensi: 60,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: "Dinas Pekerjaan Umum (PU)"
  },
  {
    id: "ASP-012",
    title: "Subsidi Pupuk Tidak Tepat Sasaran",
    description: "Distribusi pupuk subsidi di kelompok tani desa kami dikuasai oleh oknum tertentu, petani kecil tidak kebagian.",
    author: "Suharto",
    time: "1 minggu yang lalu",
    category: "Pertanian",
    status: "Menunggu Approval",
    initialUpvotes: 210,
    comments: 34,
    jarak: 70,
    urgensi: 90,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-013",
    title: "Truk Overload Merusak Jalan Desa",
    description: "Banyak truk pasir dengan muatan berlebih melintasi jalan desa kami sehingga aspal hancur total.",
    author: "Andi Saputra",
    time: "2 minggu yang lalu",
    category: "Transportasi",
    status: "Menunggu Approval",
    initialUpvotes: 134,
    comments: 12,
    jarak: 85,
    urgensi: 85,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-014",
    title: "Bantuan Sosial UMKM Tersendat",
    description: "Dana bantuan modal UMKM dari pemerintah provinsi belum juga cair padahal sudah dijanjikan sejak bulan lalu.",
    author: "Rina Kusuma",
    time: "3 minggu yang lalu",
    category: "Ekonomi",
    status: "Menunggu Approval",
    initialUpvotes: 89,
    comments: 7,
    jarak: 50,
    urgensi: 75,
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: ""
  },
  {
    id: "ASP-015",
    title: "Website PPDB Error",
    description: "Server pendaftaran sekolah online down sejak pagi, orang tua murid panik tidak bisa mendaftarkan anaknya.",
    author: "Faisal Rahman",
    time: "1 bulan yang lalu",
    category: "Pendidikan",
    status: "Selesai",
    initialUpvotes: 450,
    comments: 89,
    jarak: 100,
    urgensi: 100,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    forwardedTo: "Dinas Pendidikan"
  }
];
